#!/bin/bash
#==============================================================================
# Ensure certain packages are installed. (Simple example)
#==============================================================================

. ./bash_spec

print_header 'Verify configuration'

for package in grub2 python perl
do
    it "verifies $package is installed"
    expect $package to_be_installed
done

for file in grub2 python perl
do
    it "verifies permissions on $file"
    expect $file to_have_mode rwxr-xr-x$
done

it "verifies package vlortch is not installed"
expect vlortch not to_be_installed

print_trailer
